function analytic_plot_sedi_gap(w_0_sdr, w_0_gap, w_0_sedi, ...
    x_sdr, x_gap, x_sedi, alpha_sdr, alpha_gap, alpha_sedi, x, N, color)
% equation 4 with first SDR, then GAP, last SEDIMENTS
sdr_lava = w_0_sdr * (exp(- (x-x_gap-x_sedi) / alpha_sdr) .* ...
    (sin((x-x_gap-x_sedi)/alpha_sdr) - cos((x-x_gap-x_sedi)/alpha_sdr)) - ...
    exp(- (x-x_gap-x_sedi-x_sdr) / alpha_sdr) .* ...
    (sin((x-x_gap-x_sedi-x_sdr)/alpha_sdr) ...
    - cos((x-x_gap-x_sedi-x_sdr)/alpha_sdr)));
sdr_gap = w_0_gap * (exp(- (x-x_sedi) / alpha_gap) .* ...
    (sin((x-x_sedi)/alpha_gap) - cos((x-x_sedi)/alpha_gap)) - ...
    exp(- (x-x_gap-x_sedi) / alpha_gap) .* ...
    (sin((x-x_gap-x_sedi)/alpha_gap) ...
    - cos((x-x_gap-x_sedi)/alpha_gap)));
sdr_sedi = w_0_sedi * (exp(- (x) / alpha_sedi) .* ...
    (sin((x)/alpha_sedi) - cos((x)/alpha_sedi)) - ...
    exp(- (x-x_sedi) / alpha_sedi) .* ...
    (sin((x-x_sedi)/alpha_sedi) ...
    - cos((x-x_sedi)/alpha_sedi)));

sdrs = sdr_lava + sdr_gap + sdr_sedi;
x_total = x_sdr+x_sedi+x_gap;
plot(x(floor((x_total)/200000*N)+1:N)/1000, ...
    -sdrs(floor((x_total)/200000*N)+1:N), color);

xlabel('distance from the axis [km]','Fontsize',26');
ylabel('deflection [m]','Fontsize',26');
%title('analytical solutions to SDR surfaces (eq3 and eq4 of Buck2016)'...
%    ,'Fontsize',26');
set(gca,'Fontsize',26','Linewidth',4)
%axis([0 L/1000 -8000 1000])
%axis tight;


end

